name: Deploy Backend to Render

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'pip'
          cache-dependency-path: backend/requirements.txt

      - name: Install Dependencies
        working-directory: backend
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install black pytest

      - name: Run Black Formatter
        working-directory: backend
        run: black . --check || true

      - name: Run Pytest
        working-directory: backend
        run: pytest || true

      - name: Deploy to Render
        if: github.ref == 'refs/heads/main'
        uses: JorgeLNJunior/render-deploy@v1.4.3
        with:
          service_id: ${{ secrets.RENDER_BACKEND_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          wait: true

  deploy-weaviate:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy Weaviate to Render
        uses: JorgeLNJunior/render-deploy@v1.4.3
        with:
          service_id: ${{ secrets.RENDER_WEAVIATE_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          wait: true
